[package]
name = "cpd"
version = "0.1.0"
authors = ["Pete Gadomski <pete.gadomski@gmail.com>"]

[dependencies]
failure = "0.1"
failure_derive = "0.1"
generic-array = "0.8"
log = "0.3"
nalgebra = "0.13"

[dev-dependencies]
approx = "0.1"
